services:
  backend:
    env_file:
      - .env
    build:
      context: ./app
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    depends_on:
      - database
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - BACK_PORT=${BACK_PORT}
      - BACK_KEY=${BACK_KEY}
    container_name: workshop-backend
    networks:
      - web
  
  database:
    env_file:
      - .env
    image: postgres
    container_name: workshop-database
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./database/workshop.sql:/docker-entrypoint-initdb.d/workshop.sql
    networks:
      - web

networks:
  web:
    external: false